<?php // Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'b2af960c17177e');
define('DB_PASS', '14d02b64');
define('DB_HOST', 'us-cdbr-iron-east-03.cleardb.net');
define('DB_NAME', 'heroku_bf9a61669964c0c');
?>